name: delivery
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: '1.0.0'

environment:
  sdk: ">=3.4.3 <4.0.0"
  # sdk: '>=3.5.0-152 <4.0.0'

dependencies:
  vtv_common:
    path: ../vtv_common
  flutter:
    sdk: flutter

  # ui
  flutter_svg: ^2.0.9
  flutter_native_splash: ^2.3.9
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1
  flutter_slidable: ^3.1.0
  flutter_rating_bar: ^4.0.1

  # navigation + state management
  flutter_bloc: ^8.1.3

  # storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # notification
  firebase_messaging: ^14.7.17
  flutter_local_notifications: ^17.0.0
  firebase_core: ^2.25.4
  fluttertoast: ^8.2.4

  # functional
  intl: ^0.19.0
  dartz: ^0.10.1
  provider: ^6.1.1
  get_it: ^7.6.7
  equatable: ^2.0.5
  # json: ^0.20.1

  # network
  dio: ^5.4.2+1
  connectivity_plus: ^6.0.1
  http_parser: ^4.0.2

  # dev
  logger:

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# following page: https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true

  assets:
    # - google_fonts/
    - assets/
    - assets/images/
    - assets/images/placeholders/
    - assets/icons/
